const ROLES = {
  CUSTOMER: 'CUSTOMER',
  DRIVER: 'DRIVER',
  ADMIN: 'ADMIN',
};

const SHIPMENT_STATUS = {
  CREATED: 'CREATED',
  ASSIGNED: 'ASSIGNED',
  PICKED_UP: 'PICKED_UP',
  IN_TRANSIT: 'IN_TRANSIT',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
};

// Strict Finite State Machine transition rules
const ALLOWED_TRANSITIONS = {
  [SHIPMENT_STATUS.CREATED]: [SHIPMENT_STATUS.ASSIGNED, SHIPMENT_STATUS.CANCELLED],
  [SHIPMENT_STATUS.ASSIGNED]: [SHIPMENT_STATUS.PICKED_UP, SHIPMENT_STATUS.CANCELLED],
  [SHIPMENT_STATUS.PICKED_UP]: [SHIPMENT_STATUS.IN_TRANSIT],
  [SHIPMENT_STATUS.IN_TRANSIT]: [SHIPMENT_STATUS.OUT_FOR_DELIVERY],
  [SHIPMENT_STATUS.OUT_FOR_DELIVERY]: [SHIPMENT_STATUS.DELIVERED],
  [SHIPMENT_STATUS.DELIVERED]: [],
  [SHIPMENT_STATUS.CANCELLED]: [],
};

// Permissions required for specific status transitions
const STATUS_TRANSITION_PERMISSIONS = {
  [SHIPMENT_STATUS.ASSIGNED]: [ROLES.ADMIN],
  [SHIPMENT_STATUS.CANCELLED]: [ROLES.ADMIN, ROLES.CUSTOMER],
  [SHIPMENT_STATUS.PICKED_UP]: [ROLES.DRIVER, ROLES.ADMIN],
  [SHIPMENT_STATUS.IN_TRANSIT]: [ROLES.DRIVER, ROLES.ADMIN],
  [SHIPMENT_STATUS.OUT_FOR_DELIVERY]: [ROLES.DRIVER, ROLES.ADMIN],
  [SHIPMENT_STATUS.DELIVERED]: [ROLES.DRIVER, ROLES.ADMIN],
};

module.exports = {
  ROLES,
  SHIPMENT_STATUS,
  ALLOWED_TRANSITIONS,
  STATUS_TRANSITION_PERMISSIONS,
};
